import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import ImageContainer from '../components/ImageContainer'
export default function Home() {

  const images = [
    "https://wallpaperaccess.com/full/1252417.jpg",
    "https://fondosmil.com/fondo/29364.jpg",
    "https://fondosmil.com/fondo/29366.jpg",
    "https://images3.alphacoders.com/954/thumb-1920-954241.jpg",
    "https://fondosmil.com/fondo/11773.jpg",
    "https://cdn.ngamers.net/monthly_2018_03/ws_Red_Autumn_1920x1080.jpg.c764983446194cba679411df337085b9.jpg",
    "https://cdn.wallpapersafari.com/57/87/OU7NAl.jpg",
    "https://wallpaperaccess.com/full/307329.jpg",
    "https://wallpaperaccess.com/full/1252417.jpg",
    "https://fondosmil.com/fondo/29364.jpg",
    "https://fondosmil.com/fondo/29366.jpg",
  ]
  const total = images.length
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Galeria 3D</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} style={{ "--total-image": total }}>
      <h1 style={{"color": "#ffffff", "text-align": "center"}}>FALOPA</h1>
      {images.map((image, index) => (
      <ImageContainer
        key={image}
        keyImage={index}
        imageURL={image}
        />
      ))}
      </main>
    </div>
  )
}
